# <span style="font-family:cursive;text-align:center">⬇️ Import Libraries</span>

In [1]:
import numpy as np
import pandas as pd
import glob
import os
from datasets import Dataset
import torch
# Set the display options for pandas
pd.set_option('display.max_colwidth', 200)
pd.set_option('display.max_rows', None)

In [2]:
# Set the device to cuda if available, otherwise cpu
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

# <span style="font-family:cursive;text-align:center">⬇️ Import Data</span>

In [3]:
# Load the data from a tsv file
data = pd.read_csv("/kaggle/input/demo-data/dataset/train/boxes_transcripts_labels/004a4c67-561d-4d9c-9ef2-47cb15fbdf08_document-3_page-1.tsv", header = None)
# Assign column names to the data
data.columns = ['start_index', 'end_index', 'x_top_left', 'y_top_left', 'x_bottom_right', 'y_bottom_right', 'transcript', 'field']

In [4]:
data.sample(100)

,start_index,end_index,x_top_left,y_top_left,x_bottom_right,y_bottom_right,transcript,field
307,8199,8203,889,971,919,992,other,OTHER
227,6499,6503,141,878,188,903,B--To,OTHER
88,2471,2475,139,290,214,320,Ariel,employerAddressStreet_name
106,3160,3161,1012,463,1024,477,12,OTHER
435,12565,12569,575,1516,617,1542,cages,OTHER
333,9263,9266,1174,1090,1203,1110,ties,OTHER
399,11280,11281,1017,1333,1030,1350,to,OTHER
350,9685,9690,330,1143,413,1175,Courts,OTHER
39,969,970,856,960,871,978,on,OTHER
243,6603,6605,369,876,396,896,the,OTHER
94,2628,2636,1018,279,1083,301,Dependent,OTHER
195,5690,5699,155,704,224,725,Employer's,OTHER
354,9802,9803,938,1145,963,1167,59,OTHER
252,6670,6670,183,1554,195,1570,f,OTHER
315,8424,8425,919,993,945,1014,88,OTHER
331,9090,9099,182,1069,319,1104,48-3726648,OTHER
286,7766,7766,123,1066,137,1084,b,OTHER
469,13311,13317,1360,1535,1406,1558,Service,OTHER
98,2958,2958,707,321,719,338,9,OTHER
86,2449,2452,812,257,842,278,tips,OTHER
135,3834,3841,734,445,781,466,employee,OTHER
297,7950,7952,873,957,895,976,you,OTHER
379,10777,10780,420,1286,448,1305,Last,OTHER
386,10953,10957,241,1308,266,1327,first,OTHER
234,6542,6547,503,834,555,859,Return,OTHER
483,13801,13803,449,1640,490,1670,Tax,OTHER
65,1871,1873,817,206,838,226,and,OTHER
484,13861,13869,332,1676,454,1713,Statement,OTHER
276,7099,7105,1089,911,1131,933,penalty,OTHER
363,10280,10291,1172,1187,1244,1214,instructions,OTHER
191,5619,5620,78,716,94,733,15,OTHER
453,12892,12895,369,1528,402,1548,code,OTHER
13,354,354,1043,41,1052,66,a,OTHER
54,1514,1516,1061,175,1082,195,tax,OTHER
477,13655,13658,731,1595,885,1665,2019,OTHER
327,8993,8996,890,1072,919,1095,ages,OTHER
186,5527,5528,679,670,708,694,74,OTHER
342,9515,9529,188,1112,396,1157,Flores-Robinson,OTHER
391,11108,11110,1116,1314,1141,1333,120,OTHER
421,12201,12205,995,1468,1022,1490,"tiss,",OTHER
116,3475,3477,763,400,796,420,186,OTHER
261,6865,6866,1049,902,1063,921,to,OTHER
224,6470,6473,91,861,128,886,Form,OTHER
255,6679,6685,809,872,860,898,records,OTHER
343,9531,9533,409,1105,454,1132,and,OTHER
51,1331,1333,1051,150,1090,173,.23,box4SocialSecurityTaxWithheld
478,13727,13731,1112,1614,1165,1634,FAST!,OTHER
482,13797,13799,396,1647,445,1676,and,OTHER
417,11991,11993,1198,1444,1217,1464,tax,OTHER
126,3672,3674,929,425,950,442,Day,OTHER
496,14036,14038,307,1743,336,1764,the,OTHER
442,12666,12666,1177,1524,1187,1548,.,OTHER
425,12229,12230,1183,1472,1209,1493,94,OTHER
472,13510,13514,1112,1593,1150,1613,"Safe,",OTHER
40,995,1000,1001,131,1038,153,Social,OTHER
171,5309,5313,627,648,658,670,State,OTHER
450,12825,12827,345,1533,367,1551,ZIP,OTHER
270,7058,7059,903,937,915,956,to,OTHER
19,551,556,1038,73,1081,96,income,OTHER
405,11368,11374,394,1366,508,1403,Landing,OTHER
408,11537,11538,1227,1393,1249,1413,25,OTHER
267,6901,6903,1247,877,1273,897,you,OTHER
247,6641,6643,564,904,589,925,Cut,OTHER
147,4409,4415,289,510,404,548,Landing,OTHER
216,6241,6247,424,742,522,776,40864.2,OTHER
380,10782,10785,449,1281,487,1301,name,OTHER
242,6600,6601,351,879,369,899,to,OTHER
298,7954,7957,1088,931,1104,951,fail,OTHER
78,2310,2312,203,230,226,250,and,OTHER
14,356,356,214,126,226,144,a,OTHER
198,5750,5752,241,683,263,702,ZIP,OTHER
319,8766,8773,842,1045,956,1075,74643.59,OTHER
193,5648,5652,98,712,133,732,State,OTHER
64,1865,1869,774,208,814,231,wages,OTHER
174,5337,5341,793,649,863,678,78347,OTHER
118,3522,3524,1005,397,1021,411,126,OTHER
356,9836,9844,1124,1142,1189,1167,Decendent,OTHER
101,3133,3133,938,933,946,951,a,OTHER
133,3743,3745,198,437,219,455,and,OTHER
258,6846,6847,977,945,989,965,is,OTHER
66,1875,1878,841,204,861,223,tips,OTHER
115,3364,3369,103,394,149,416,number,OTHER
353,9786,9791,855,1148,936,1174,74643.,OTHER
497,14040,14043,337,1737,376,1760,back,OTHER
140,4132,4133,721,497,741,516,14,OTHER
47,1274,1279,713,167,750,187,Social,OTHER
202,5876,5883,417,692,530,724,38337.36,OTHER
146,4403,4407,196,524,277,558,Jamie,OTHER
419,12022,12029,1332,1457,1398,1477,Motorway,OTHER
103,3139,3150,1066,322,1140,347,instructions,OTHER
26,747,747,1073,98,1083,119,1,box2FederalIncomeTaxWithheld
56,1527,1527,16,200,29,218,b,OTHER
492,13975,13978,496,1695,533,1719,(See,OTHER
443,12668,12669,1189,1521,1215,1547,98,OTHER
337,9316,9318,308,1093,331,1115,and,OTHER
415,11978,11982,1117,1452,1149,1472,Local,OTHER
67,2003,2007,741,235,812,260,98904,OTHER
377,10702,10705,1110,1258,1132,1274,1213,OTHER
278,7302,7307,1123,925,1156,947,report,OTHER
220,6395,6398,225,805,290,833,Wage,OTHER

In [5]:
data['field'].unique()

array(['OTHER', 'box2FederalIncomeTaxWithheld', 'ssnOfEmployee',
       'box1WagesTipsAndOtherCompensations',
       'box4SocialSecurityTaxWithheld', 'box3SocialSecurityWages',
       'einEmployerIdentificationNumber', 'employerName',
       'employerAddressStreet_name', 'employerAddressState',
       'employerAddressZip', 'employerAddressCity', 'employeeName',
       'taxYear', 'box17StateIncomeTax', 'box16StateWagesTips'],
      dtype=object)

In [6]:
# Define a dictionary of ner labels and their corresponding numeric codes
ner_labels = { 0 : "OTHER",
1 : "employerName",
2 : "employerAddressStreet_name",
3 : "employerAddressCity",
4 : "employerAddressState",
5 : "employerAddressZip",
6 : "einEmployerIdentificationNumber",
7 : "employeeName",
8 : "ssnOfEmployee",
9 : "box1WagesTipsAndOtherCompensations",
10 : "box2FederalIncomeTaxWithheld",
11 : "box3SocialSecurityWages",
12 : "box4SocialSecurityTaxWithheld",
13 : "box16StateWagesTips",
14 : "box17StateIncomeTax",
15 : "taxYear"
}

In [7]:
# Create a reverse dictionary of ner labels and their numeric codes
ner_labels_dict = {}
for key in ner_labels.keys():
    ner_labels_dict.update({ner_labels[key] : key})

In [8]:
ner_labels_dict

{'OTHER': 0,
 'employerName': 1,
 'employerAddressStreet_name': 2,
 'employerAddressCity': 3,
 'employerAddressState': 4,
 'employerAddressZip': 5,
 'einEmployerIdentificationNumber': 6,
 'employeeName': 7,
 'ssnOfEmployee': 8,
 'box1WagesTipsAndOtherCompensations': 9,
 'box2FederalIncomeTaxWithheld': 10,
 'box3SocialSecurityWages': 11,
 'box4SocialSecurityTaxWithheld': 12,
 'box16StateWagesTips': 13,
 'box17StateIncomeTax': 14,
 'taxYear': 15}

In [9]:
# Create a new column in the data with the numeric codes for the ner tags
data['ner_tags'] = data['field'].map(lambda x: ner_labels_dict[x])

In [10]:
# Convert the ner tags column to a list
data['ner_tags'].to_list()

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 10,
 10,
 0,
 0,
 0,
 0,
 0,
 8,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 9,
 9,
 9,
 0,
 0,
 0,
 12,
 12,
 11,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 6,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 2,
 4,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 7,
 7,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 15,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 14,
 14,
 14,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 13,
 13,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [11]:
# Convert the transcript column to a list
data['transcript'].to_list()

['12a',
 'being',
 'This',
 'information',
 'compensation',
 'Visit',
 'the',
 'IRS',
 'Website',
 'Safe,',
 'Accurate,',
 're',
 'file',
 'a',
 'a',
 'www.irs.goviefile',
 'FAST!',
 'Use',
 'Federal',
 'income',
 'tax',
 'withheld',
 'OMB',
 'No.',
 '1545-0008',
 '24033.',
 '1',
 'a',
 "Employee's",
 'social',
 'security',
 'number',
 '380-62-5767',
 'Wages,',
 'tips,',
 'other',
 'c',
 'e',
 'at',
 'on',
 'Social',
 'security',
 'tax',
 'withheld',
 '80470',
 '.',
 '88',
 'Social',
 'security',
 'wages',
 '5710',
 '.23',
 '74643.59',
 'Medicare',
 'tax',
 'withheld',
 'b',
 'Employer',
 '48-3726648',
 'identification',
 'number',
 '(EIN)',
 '2868.23',
 'Medicare',
 'wages',
 'and',
 'tips',
 '98904',
 '.',
 '37',
 'Allocated',
 '98904.',
 'tips',
 '37',
 'c',
 "Employer's",
 'name,',
 'address,',
 'and',
 'Flores-Robinson',
 'and',
 'Sons',
 'ZIP',
 'code',
 'Social',
 'security',
 'tips',
 '364',
 'Ariel',
 'Courts',
 'AK',
 '12316-9561',
 '74643.59',
 '10',
 'Dependent',
 'care',
 '232',
 'benefits',
 '9',
 'Amandatown',
 '12',
 'a',
 'See',
 'instructions',
 'for',
 'box',
 '12',
 'Suff.',
 '11',
 'Nonqualified',
 'plans',
 'M',
 '3575',
 'd',
 'Control',
 'number',
 '186',
 'Third-party',
 '126',
 '7932918',
 'Last',
 'name',
 '13',
 'Statutory',
 'Retiremer',
 'sick',
 'Day',
 'D',
 '137',
 'e',
 "Employee's",
 'first',
 'name',
 'and',
 'initial',
 'employee',
 '1',
 'X',
 'John',
 'Simmons',
 '14',
 'Other',
 'BB',
 '108',
 '12d',
 '6740',
 'Jamie',
 'Landing',
 'co',
 '61686-571',
 '925',
 'East',
 'Anthonyfurt',
 '20',
 'Locality',
 'name',
 '19',
 'Local',
 'income',
 'tax',
 'David',
 'Motorway',
 '18',
 'Local',
 'wages,',
 'tips,',
 'etc',
 '12230',
 '.',
 '94',
 '17',
 'State',
 'income',
 'tax',
 '78347',
 '.',
 '02',
 'Jon',
 'Port',
 '16',
 'State',
 'wages,',
 'tips,',
 'etc.',
 '4822',
 '.',
 '74',
 '12177',
 '.',
 '98',
 'f',
 '15',
 "Employee's",
 'State',
 'address',
 "Employer's",
 'and',
 'state',
 'ZIP',
 'ID',
 'code',
 'number',
 '38337.36',
 '98770',
 '.',
 '09',
 '679-27-607',
 '4547.',
 '35',
 'Department',
 'of',
 'the',
 'Treasury--Internal',
 'Revenue',
 'Service',
 'OK',
 '40864.2',
 '470-56-735',
 '2019',
 'AZ',
 'Wage',
 'and',
 'Tax',
 'Statement',
 'Form',
 'W-2',
 'Copy',
 'B--To',
 'Be',
 'Filed',
 'with',
 "Employee's",
 'FEDERAL',
 'Tax',
 'Return',
 'is',
 'for',
 'a',
 'on',
 'is',
 'being',
 'furnished',
 'to',
 'the',
 'Internal',
 'Revenue',
 'Service.',
 'Cut',
 'here.',
 'Keep',
 'lower',
 'portion',
 'f',
 'or',
 'your',
 'records',
 'his',
 'information',
 'is',
 'be',
 'furnished',
 'to',
 'the',
 'internal',
 'Revenue',
 'Service.',
 'If',
 'you',
 'are',
 'required',
 'to',
 'file',
 'tax',
 'return,',
 'negligence',
 'Federal',
 'penalty',
 'to',
 'report',
 'income',
 'it.',
 'other',
 'tax',
 'sanction',
 'withheld',
 'may',
 'b',
 'imposed',
 'OMB',
 'No.',
 '1545-0008',
 'you',
 'if',
 'this',
 'income',
 'taxable',
 'and',
 'you',
 'fail',
 '24033.1',
 "Employee's",
 'social',
 'security',
 '380-62-5767',
 'number',
 'Wages,',
 'tips,',
 'other',
 'compensation',
 'Social',
 'security',
 'tax',
 'withheld',
 '80470',
 '.',
 '88',
 'Social',
 'security',
 '5710.23',
 '74643.59',
 'tieare',
 'tax',
 'withheld',
 'Employer',
 'identification',
 'number',
 'Medicare',
 'ages',
 'and',
 'tips',
 '2868.23',
 '48-3726648',
 'Allocated',
 'ties',
 "Employer's",
 'name,',
 'address,',
 'and',
 'ZIP',
 'code',
 '98904.37',
 '98904.37',
 'Flores-Robinson',
 'and',
 'Sons',
 'Social',
 'security',
 'tips',
 '364',
 'Ariel',
 'Courts',
 'AK',
 '12316-9561',
 '74643.',
 '59',
 '1/',
 'Decendent',
 'care',
 '232',
 'Benefits',
 'Amanda',
 'town',
 'See',
 'instructions',
 'for',
 'box',
 '12',
 'Suff.',
 '11',
 'Honqualified',
 'plans',
 'M',
 '3575',
 'd',
 'Control',
 'number',
 '186',
 '1213',
 '7932918',
 'Last',
 'name',
 '13',
 'statutory',
 'D',
 '137',
 "Employee's",
 'first',
 'name',
 'and',
 'initial',
 'X',
 '120',
 'John',
 'Simmons',
 '14',
 'Other',
 'isee',
 'enclosed',
 'flotice',
 'to',
 'Employee;',
 'BB',
 '108',
 '6740',
 'Jamie',
 'Landing',
 'CO',
 '61686-571',
 '25',
 'East',
 'Anthonyfurt',
 '20',
 'Locality',
 'name',
 '19',
 'Local',
 'income',
 'tax',
 'David',
 'Motorway',
 'ages,',
 'tiss,',
 'etc.',
 '12230',
 '.',
 '94',
 'income',
 'tax',
 '78347',
 '.',
 '02',
 'Jon',
 'P',
 '16',
 'State',
 'cages',
 'tips,',
 'etc',
 '4822',
 '.',
 '74',
 '12177',
 '.',
 '98',
 '15',
 "Employee's",
 'State',
 'address',
 "Employer's",
 'and',
 'ZIP',
 'state',
 'ID',
 'code',
 'number',
 '38337.',
 '36',
 '98770',
 '.',
 '09',
 '679-27-607',
 '4547',
 '.',
 '35',
 'Department',
 'of',
 'the',
 'Treasury--Internal',
 'Revenue',
 'Service',
 'OK',
 '40864.2',
 'Safe,',
 'accurate,',
 're',
 'file',
 '170-56-735',
 '2019',
 'FAST!',
 'Use',
 'AZ',
 'Wage',
 'and',
 'Tax',
 'Statement',
 'Form',
 'W-2',
 'Copy',
 'C',
 'For',
 "EMPLOYEE'S",
 'RECORDS.',
 '(See',
 'Notice',
 'to',
 'mployee',
 'the',
 'back',
 'of',
 'Copy',
 "B.)'"]

In [12]:
# Get the unique values of the ner tags column
data['ner_tags'].unique()

array([ 0, 10,  8,  9, 12, 11,  6,  1,  2,  4,  5,  3,  7, 15, 14, 13])

In [13]:
# Define a function to load data from a given path
def load_data(path):
    directory = path
    # Get all the tsv files in the directory
    tsv_file = glob.glob(directory + '/*.tsv')
    # Create an empty dataframe with two columns: transcript and ner_tags
    data = pd.DataFrame(columns = ['transcript', 'ner_tags'])
    # Loop through each tsv file in the directory
    for filename in tsv_file:
        # Read the tsv file as a dataframe
        data_i = pd.read_csv(filename, header=None)
        # Assign column names to the dataframe
        data_i.columns = ['start_index', 'end_index', 'x_top_left', 'y_top_left', 'x_bottom_right', 'y_bottom_right', 'transcript', 'field']
        # Drop any rows that have missing values in the transcript column
        data_i.dropna(subset=['transcript'], inplace=True)
        # Convert the transcript column to a list
        transcript = data_i['transcript'].to_list()
        # Map the field column to the numeric codes using the reverse dictionary
        data_i['field'] = data_i['field'].map(lambda x: ner_labels_dict[x])
        # Convert the field column to a list of ner tags
        ner_labels = data_i['field'].to_list()
        # Get the length of the transcript list
        transcript_len = len(transcript)
        
        # If the transcript list is longer than 300, split it into two parts and append them as separate rows in the data dataframe
        if transcript_len > 300:
            transcript_1 = transcript[:(transcript_len//2)]
            ner_labels_1 = ner_labels[:(transcript_len//2)]
            transcript_2 = transcript[(transcript_len//2):]
            ner_labels_2 = ner_labels[(transcript_len//2):]
            data.loc[len(data)] = [transcript_1, ner_labels_1]
            data.loc[len(data)] = [transcript_2, ner_labels_2]
        # Otherwise, append the transcript list and the ner tags list as a single row in the data dataframe    
        else:
            data.loc[len(data)] = [transcript, ner_labels]
    # Return the data dataframe
    return data

In [14]:
%%time
# Measure the execution time of loading the train and validation data
train_data = load_data('/kaggle/input/demo-data/dataset/train/boxes_transcripts_labels')
val_data = load_data('/kaggle/input/demo-data/dataset/val_w_ann/boxes_transcripts_labels')

CPU times: user 4.04 s, sys: 105 ms, total: 4.15 s
Wall time: 6.26 s

In [15]:
train_data.loc[0]

transcript    [(C-Box, Profile., Information,, Medicare, :46, 88415, Employer's, 1653.98, Employee, Reference, W-2, Wage, !, ), and, Tax, Copy, 2018, W-2, and, EARNINGS, SUMMARY, Stateme, Copy, C, for, employee...
ner_tags      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
Name: 0, dtype: object

In [16]:
val_data.head()

,transcript,ner_tags
0,"[1, Wages,, tips,, other, comp., 2, Federal, income, tax, withheld, 76710.3, 11444.41, 3, Social, security, wages, 4, Social, security, tax, withheld, 90562.66, 6928.04, 5, Medicare, wages, and, t...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 4, 5, 0, 0, ..."
1,"[a, Employee's, social, security, number, Safe,, Accurate., Visit, the, IRS, Website, Re, ~, file, 071-51-2027, OMB, No., 1545-0008, FAST!, US, at, www.irs.gov/efile., b, Employer, identification,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 9, 9, 10, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 11, 11, 11, 12, 12, 12..."
2,"[Information,, 2018AOP., ex, 224720.73, Employee, Reference, W-2, and, Tax, 2018, W-2, and, EARNINGS, SUMMARY, 2018, This, blue, Earnings, Summary, section, is, included, with, your, W-2, to, help...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0,..."
3,"[17, State, inco, STATE:, 6535.39, 142808., etc., 62, 19, Local, income, tax, Local, wages,, tips,, Locality, name, Wages,, tips,, other, ., 2018, LLC, Social, sexy, me, tax, win, 209331, -92, led...","[0, 0, 0, 0, 14, 13, 0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,"[23838.77, Medicare, tax, 2018, W-2, and, EARNINGS, SUMMARY, ADP, Employee, Reference, Copy, his, blue, Earnings, Summary, section, is, included, with, your, W-2, to, help, describe, portions, in,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."

In [17]:
train_data.shape, val_data.shape

((844, 2), (284, 2))

# Transformer preprocessing

In [18]:
# Show the first row of the train data
from transformers import AutoTokenizer
# Load the tokenizer for the distilbert-base-uncased model
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

Downloading (…)okenizer_config.json:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading (…)lve/main/config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

Downloading (…)solve/main/vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading (…)/main/tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [19]:
# Get the first transcript and ner tags from the train data
example_1 = train_data['transcript'][0]
ner = train_data['ner_tags'][0]

In [20]:
# Tokenize the transcript using the tokenizer
tokens = tokenizer(example_1, is_split_into_words=True, truncation=True)
# Show the tokens
tokens

{'input_ids': [101, 1006, 1039, 1011, 3482, 6337, 1012, 2592, 1010, 27615, 1024, 4805, 6070, 23632, 2629, 11194, 1005, 1055, 29309, 1012, 5818, 7904, 4431, 1059, 1011, 1016, 11897, 999, 1007, 1998, 4171, 6100, 2760, 1059, 1011, 1016, 1998, 16565, 12654, 2110, 4168, 6100, 1039, 2005, 7904, 1005, 1055, 1040, 2491, 2193, 29466, 1012, 13058, 1012, 2023, 2630, 16565, 12654, 2930, 2003, 2443, 2007, 2115, 1059, 1011, 1016, 2000, 2393, 6235, 8810, 1999, 2062, 6987, 2760, 1996, 7901, 2217, 2950, 2236, 2592, 2008, 2017, 2089, 2036, 2424, 14044, 1012, 29466, 5018, 18168, 2497, 2053, 1012, 16666, 2629, 1011, 2199, 2620, 11194, 1005, 1055, 2171, 1010, 4769, 1010, 1998, 14101, 3642, 11194, 2224, 2069, 8685, 1011, 3817, 15492, 4748, 2361, 1015, 1012, 1996, 2206, 2592, 11138, 2115, 2345, 2760, 3477, 24646, 2497, 4606, 2151, 24081, 7864, 2011, 2115, 11194, 1012, 21064, 2581, 2575, 5655, 3137, 2225, 17217, 2139, 6070, 23632, 2629, 1011, 5641, 2620, 2487, 7977, 3477, 7886, 22907, 2581, 1019, 2591, 3036, 6275, 2581, 2581, 1018, 1020, 7349, 1012, 3318, 3482, 1018, 1997, 1059, 3501, 17163, 5126, 2171, 1010, 4769, 1998, 14108, 14101, 3642, 13029, 16048, 1012, 6163, 1059, 2615, 1012, 2110, 3318, 4171, 1001, 6185, 2692, 17465, 3482, 4171, 1016, 2007, 24850, 1997, 1059, 1011, 1016, 27615, 4171, 3482, 2459, 1997, 1059, 1012, 1016, 29309, 5818, 10294, 16672, 2007, 24850, 12875, 2692, 1012, 1022, 3482, 2539, 1997, 1059, 1011, 1016, 14677, 20958, 1012, 1023, 14677, 22394, 2665, 2691, 7621, 6021, 2475, 3482, 1020, 1997, 1059, 1012, 1016, 6262, 16917, 18712, 24086, 1013, 17371, 2072, 1013, 13109, 2072, 10715, 17914, 1011, 4466, 21057, 3482, 2403, 1997, 1059, 1012, 1016, 1016, 1012, 2115, 7977, 3477, 2001, 10426, 2004, 4076, 2000, 3965, 2115, 1059, 1011, 1016, 4861, 1012, 1038, 11194, 1005, 1055, 7349, 8909, 2193, 4261, 1011, 5345, 11387, 26224, 2581, 14855, 7904, 1005, 1055, 7020, 2050, 2193, 3770, 13871, 10247, 1010, 2060, 4012, 2361, 1012, 1017, 2591, 3036, 12678, 1016, 2976, 3318, 6282, 2487, 1011, 2676, 1011, 5511, 17788, 4171, 2007, 24850, 12678, 1010, 10247, 1010, 2060, 9430, 3482, 1997, 4576, 2591, 10819, 10179, 2966, 1018, 2591, 3036, 4171, 2007, 24850, 4606, 14181, 2140, 3482, 3482, 12678, 1017, 1997, 1059, 1012, 1016, 12678, 3482, 1019, 1997, 1059, 1012, 1016, 10247, 1010, 1059, 2615, 1012, 2110, 4385, 1012, 12678, 1010, 18243, 2378, 2685, 1019, 27615, 12678, 1998, 10247, 9686, 2015, 22649, 1006, 1047, 1007, 1006, 1040, 1011, 3482, 12606, 1016, 1007, 3482, 2385, 1997, 1059, 1012, 1016, 5824, 22932, 2487, 1012, 4720, 27615, 4171, 2007, 24850, 2988, 1059, 1011, 1016, 12678, 6356, 27009, 7886, 22907, 2581, 1012, 3429, 2591, 3036, 10247, 13029, 16048, 1012, 6163, 7886, 22907, 2581, 6356, 27009, 1038, 2324, 1997, 1059, 2475, 9402, 2683, 2581, 2509, 1012, 3943, 1022, 11095, 12875, 2692, 10247, 1012, 1022, 13029, 2385, 1012, 6163, 5003, 6356, 27009, 2629, 1023, 22616, 3642, 1017, 1012, 7904, 1059, 1011, 1018, 6337, 1012, 2000, 2689, 2115, 7904, 3770, 2575, 2620, 2509, 1012, 3590, 13029, 16048, 1012, 6163, 2005, 1037, 1010, 1059, 1011, 1018, 5371, 7886, 18827, 2581, 1019, 2007, 2115, 26854, 29466, 1012, 6273, 2683, 1006, 3429, 2549, 2047, 1059, 1011, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [21]:
# Define a function to tokenize a given data
def tokenize_func(data):
    # Return the tokenized transcript using the tokenizer
    return tokenizer(data['transcript'], is_split_into_words=True, truncation=True)

In [22]:
# Define a function to tokenize a given data
def tokenize_data(data):
    # Convert the data to a Dataset object from the datasets library
    data = Dataset.from_pandas(data)
    # Apply the tokenize function to the data and map it to a new column
    data = data.map(tokenize_func)
    # Remove the index column from the data
    data = data.remove_columns(['__index_level_0__'])
    # Return the data as a pandas dataframe
    return data.to_pandas()

In [23]:
# Get the transcript column from the train data
train_data['transcript']

0      [(C-Box, Profile., Information,, Medicare, :46, 88415, Employer's, 1653.98, Employee, Reference, W-2, Wage, !, ), and, Tax, Copy, 2018, W-2, and, EARNINGS, SUMMARY, Stateme, Copy, C, for, employee...
1      [Dept., 2, Federal, income, tax, withheld, Employer's, name,, address, ,, and, ZIP, code, security, wages, Lopez-Daniel, PLC, Employer, use, only, Medicare, wages, and, 4, Social, security, tax, w...
2      [Wages,, tips,, other, comp., 2, Federal, income, tax, withheld, 240330, ., 89, 35494, ., 65, 3, Social, security, wages, 4, Social, security, tax, withheld, 280634.5, 21468, .54, 5, Medicare, wag...
3      [1, Wages,, tips,, other, comp., 2, Federal, income, tax, withheld, 233146.9, 73449.38, 3, Social, security, wages, 4, Social, security, tax, withheld, 208770.54, 15970.95, 5, Medicare, wages, and...
4      [23593.7, 18732.51, 245653.79, name,, address,, W-2, 2018, W-2, and, EARNINGS, SUMMARY, ADP, Employee, Reference, Copy, his, blue, Earnings, Summary, section, is, included, with, your, W-2, to, he...
5      [income, tax, withhel, Social, security, wages, 4, Social, security, tax, withheld, Social, security, way, Social, security, tax, withheld, Social, security, wag, 4, Social, security, tax, withhel...
6      [a, Employee's, social, security, number, Safe,, Accurate., Visit, the, IRS, Website, Re, ~, file, 206-89-2179, OMB, No., 1545-0008, FAST!, US, at, www.irs.gov/efile., b, Employer, identification,...
7      [a, Employee's, social, security, number, Safe,, Accurate., Visit, the, IRS, Website, RSe, ~, file, 290-12-4455, OMB, No., 1545-0008, FAST!, US, at, www.irs.gov/efile., b, Employer, identification...
8      [31971.4, 53, 07163-2448, 4381, Sara, 2018, W-2, and, EARNINGS, SUMMARY, ADP, Employee, Reference, Copy, his, blue, Earnings, Summary, section, is, included, with, your, W-2, to, help, describe, p...
9      [tax, 15383, ., 65, 6, withhel2, 201095-41, 15383., 6, 201093, .41, 15383, ., 5, 65, Medicare, wages, and, tips, 6, Medicare, tax, withheld, 63, 17, 6989, 5, and, ti, Medicare, tax, withheld, 1759...
10     [5238., This, 12a, number, and, Visit, the, IRS, Website, Safe,, Accurate,, me, file, at, www.irs, govefile., a, Employee's, social, security, number, OMB, No., 1545-000, FAST!, Use, Federal, inco...
11     [to, the, Internal, Revenue, Service., If, you, are, Employee's, social, security, be, OMB, No., 1545-0008, on, required, to, file, tax, return,, negligence, penalty, income, you, if, this, income...
12     [a, Employee's, social, security, number, Safe,, Accurate,, file, Visit, the, IRS, Website, OMB, No., 1545-0908, FAST!, Use, re+, 579-24-1268, at, www.irs, gov, efile, b, Employer, identification,...
13                                                                                                                                                                 [2018, W-2, and, EARNINGS, SUMMARY, The, E]
14     [12a, 18., Visit, the, IRS, Website, Safe,, Accurate,, IRe, file, at, www.irs.gov/efile., OMB, No., 1545-0008, FAST!, Use, 2, Federal, income, tax, withheld, a, Employee's, social, security, numbe...
15     [27053.04, 5905, 2615.72, security, 86588, 142367., 2018, W-2, and, EARNINGS, SUMMARY, FDP, employee, Reference, Cop, This, blue, Earnings, Summary, section, is, included, with, your, W-2, to, hel...
16     [tax, withheld, Social, security, wages, Social, security, tax, withheld, 86588.28, 86588, .28, 6624, ., 86588, ., 28, 6624, ., Medicare, .4, wages, and, tips, Medicare, ta, Medicare, 90197, wages...
17                                                                                                                                                                    [2018, !!', W-2, and, EARNINGS, SUMMARY]
18     [77796.34, 3759.51, withheby, 2018, W-2, and, EARNINGS, SUMMARY, ADP, Employee, Reference, Copy, his, blue, Earnings, Summary, section, is, included, with, your, W-2, to, help, describe, portions,...
19     [Social, security, tax, withheld, 49143, ., 87, 3759, .51, 3759, ., 51, 49145-87, Medicare, tax, 5, ., 5, 1, 25, with, he, 6, Medicare, tax, withheld, 49145-87, Medicare, wages, and, tips, Medicar...
20     [809-21-4576, 8, ., file, 43-4391249, 234070.02, 53010-74, nicholson-Dunn, Ltd, 186013.35, 14230.02, 40370, mernandez, Plains, Meet, Brenda, 0, 17089-0725, 223596.67, 6404.3, 186013.35, 223596.67,...
21     [Service, 95-7356736, 380-25-7673, Kelly, PLC, Ltd, Safe., Accurate., FAST!, Use, cefile, 42488, Mann, Highway, Apt., 717, Visit, the, 15, Website, 59814.81, at, wow, its, govieffie, Tannerville, ...
22     [a, Employee's, social, security, number, Safe,, Accurate., Visit, the, IRS, Website, 372-90-4537, Rev, file, OMB, No., 1545-0008, FAST!, Us, at, www.irs.gov/efile, b, Employer, identification, nu...
23     [Internal, Revenue, Service., If, you, are, required, 372-90-4537, OMB, No., 1545-0008, to, file, a, tax, return,, a, negligence, penalty, or, other, sanction, may, be, imposed, on, you, if, this,...
24     [a, Employee's, social, security, number, Safe,, Accurate,, Re, file, at, Visit, the, IRS, Website, 257-02-8934, OMB, No., 1545-0008, FAST!, Use, www.Irs.gov/efile., b, Employer, identification, n...
25     [1, Wages,, tips,, other, comp., Federal, income, tax, withheld, 67328, ., 87, 10223, ., 79, 3, Social, security, wages, 4, Social, security, tax, withheld, 63436, ., 14, 4852, ,, 86, 5, Medicare,...
26     [Randall, Visit, the, IRS, Website, Safe,, Accurate,, re, +, file, at, www.irs, govefile, FAST!, Use, 2, Federal, income, tax, withheld, OMB, No., 1545-0008, 26578, ., 19, Employee's, social, secu...
27     [Wages,, tips,, other, comp., 2, Federal, income, tax, withheld, 202897, ., 03, 58593, ., 47, 3, Social, security, wages, 4, Social, security, tax, withheld, 196502, ., 25, 15032, ., 42, 5, Medica...
28     [2018, W-2, and, EARNINGS, SUMMARY, alone, in, more, diefall, his, included, witt, your, Wi-2, no, help, dies, This, Blue, Earnings, Summary, The, reverse, side, includes, general, information, th...
29     [311-89-7688, FAST, Use, e-file, 04-4091485, 128754.19, 40015.89, Scott, LLC, and, Sons, 109518.2, 8378.14, 553, Warren, Course, Suite, 807, 24625-0241, 140371.75, 4070.78, Levisland, WI, 109518.2...
30     [11274-., a, Employee's, social, security, number, Safe,, Accurate,, Visit, the, IRS, Website, 748-16-1689, OMB, No., 1545-0008, FAST!, Use, rev, file, at, www.irs, goviefile, b, Employer, identif...
31     [If, you, are, 748-16-1689, OMB, No., 1545-0008, required, to, file, a, tax, return,, a, negligence, penalty, or, other, sanction, may, be, imposed, on, you, if, this, income, is, taxable, and, yo...
32     [2018, W-2, and, EARNINGS, SUMMARY, ADP, Employee, Reference, Copy, his, blue, Earnings, Summary, section, is, included, with, your, W-2, to, help, describe, portions, in, more, detail., Wage, and...
33     [Medicare, wages, and, tips, Medicare, tax, withheld, ,, 65, 96849-, 92, 6, Medicare, tax, 7409.02, withheld, 65, 95849., 92, Medicare, wades, a, 7409, .02, 5, Medicare, tax, withheld, dicgre, wag...
34     [a, Employee's, social, security, number, Safe,, Accurate., Visit, the, IRS, Website, Rev, file, 197-71-1499, OMB, No., 1545-0008, FAST!, Us, at, www.irs.gov/efile, er, identification, number, (EI...
35     [Revenue, Service., If, you, are, required, 197-71-1499, OMB, No., 1545-0008, to, file, a, tax, return,, a, negligence, penalty, or, other, sanction, may, be, imposed, on, you, if, this, income, i...
36     [Wages,, tips,, other, comp., 2, Federal, income, tax, withheld, 97993, ., 64, 27072, ., 16, 3, Social, security, wages, 4, Social, security, tax, withheld, 118640.22, 9091.28, 5, Medicare, wages,...
37     [069-53-143, Stacey, 2018, W-2, and, EARNINGS, SUMMARY, AP, Employee, Reference, Copy, This, blue, Earnings, Summary, section, is, included, with, your, W-2, to, help, describe, portions, in, more...
38     [STATE, Alexanderton, AK, LOCAL, ified, plans, be, instructions, for, box, 12, 14, Other, 1, 9546, 15, Employers', 1, state, ID, na., 16, 1, Scase, wages,, tips,, ese., 24317.59, State, income, ta...
39     [compensation, 86, Apt., a, Employee's, social, security, number, b, Employer, identification, number, (EIN), 412-52-5042, Safe,, Accurate,, 14-2133094, OMB, No., 1545-0008, FAST!, Use, ORse, file...
40     [Accurate,, 12a, This, Visit, the, IRS, Website, Safe,, c, at, e, re, ~, file, a, www.irs, gov.efile, FAST!, Use, Federal, income, tax, withheld, OMB, No., 1545-0008, 24172., 22, Employee's, socia...
41     [a, Employee's, social, security, number, Safe,, Accurate., Visit, the, IRS, Website, RSe, ~, file, $28-01-0124, OMB, No., 1545-0008, FAST!, US, at, www.irs.gov/efile., b, Employer, identification...
42     [a, Employee's, social, security, number, Safe,, Accurate., Visit, the, IRS, Website, Re, ~, file, 278-69-7877, OMB, No., 1545-0008, FAST!, US, at, www.irs.gov/efile., b, Employer, identification,...
43     [This, Earnings, was, Profile., 185890.37, withheld, Control, name,, 12a, Andersonland, Locality, Statement, ADP, 2018, W-2, and, EARNINGS, SUMMARY, is, blue, a, in, Summary, section, i, included,...
44     [Neck, Social, security, wages, 6, Medicare, tax, withheld, 3138, .2, 236890.91, Employer, use, 36, only, 2, Federal, income, 24998.29, tax, withheld, Medicare, wages, and, 19, Local, in, 28506.89...
45     [0061, 3., Medicare, Trail, 2018, W-2, and, EARNINGS, SUMMARY, ADP, Employee, Reference, Copy, his, blue, Earnings, Summary, section, is, included, with, your, W-2, to, help, describe, portions, i...
46     [security, wage, Social, security, tax, withheld, 70404-51, care, tax, 5385, ., 95, 95, withheld, 10404., 51, 5385.95, Medicare, tax, withheld, ., 95, 5385, -, 35, they, a, wanes, and, tips, edica...
47     [Wages,, tips,, other, comp., 2, Federal, income, tax, withheld, 240216, ., 54, 33660, .7, 3, Social, security, wages, 4, Social, security, tax, withheld, 173334., 74, 13260, ., 11, 5, Medicare, w...
48     [17490., 175025., victoria, 2018, W-2, and, EARNINGS, SUMMARY, FDP, Employee, Reference, Cop, This, blue, Earnings, Summary, section, is, included, with, your, W-2, to, help, describe, portions, i...
49     [security, wages, Social, security, 1, 7, ., tax, withheld, 31, 228500, ., 77, 17480, .31, 228500.77, 228500, Medicare, wages, and, tips, 5, Medicare, tax, withheld, care, wages, and, tips, Medica...
50     [a, Employee's, social, security, number, Safe,, Accurate,, Visit, the, IRS, Website, 207-09-8027, OMB, No., 1545-0008, FAST!, Use, ce, +, file, at, www.irs, gov, efile, b, Employer, identificatio...
51     [207-09-8027, OMB, No., 1545-0008, on, required, to, file, a, tax, return,, a, negligence, penalty, or, other, sanction, may, be, imposed, you, if, this, income, is, taxable, and, you, 2, fail, Fe...
52     [a, Employee's, social, security, number, Safe,, Accurate., Visit, the, IRS, Website, Re, ~, file, 079-65-9252, OMB, No., 1545-0008, FAST!, Us, at, www.irs.gov/efile., b, Employer, identification,...
53     [This, compensation, 12a, number, Safe,, Accurate,, inse, Visit, the, IRS, Website, ~, file, a, a, www.irs.gov/efile, a, Employee's, social, security, number, 051-70-0598, OMB, No., 1545-0008, FAS...
54     [furnished, to, the, Internal, Revenue, Service., If, you, are, a, Employee's, social, security, be, OMB, No., 1545-0008, required, to, file, tax, return,, negligence, penalty, or, other, sanction...
55     [any, Notice, Safe,, Accurate., ce, ~, file, Visit, the, IRS, Website, 875-34-1319, FAST!, Use, at, www, irs, govefile, b, Employer, ideenif, mber, ED, Wages,, hips., offher, co, Federal, income, ...
56     [Senlice., IF, you, are, 875-34-1319, OnD, The., 1545-0609, a, required, you, if, to, this, file, income, a, tax, lis, reform,, taxable, an, negligence, you, fail, penalty, to, meagit, or, other, ...
57     [172, ages,, tips,, other, comp, income, tax, 71207.69, Social, security, wages, $1426.05, 71639.61, Social, security, tax, withheld, Medicare, wages, 5490-43, 73972.06, Medicare, tax, 2145.19, 70...
58     [a, Employee's, social, security, number, Safe,, Accurate., Visit, the, IRS, Website, Re, ~, file, 310-75-6792, OMB, No., 1545-0008, FAST!, Us, at, www.irs.gov/efile., b, Employer, identification,...
59     [Wages,, tips,, other, comp., 2, Federal, income, tax, withheld, 158916.89, 34883.22, 3, Social, security, wages, 4, Social, security, tax, withheld, 142978, ., 09, 10937, ., 82, 5, Medicare, wage...
60     [a, Employee's, social, security, number, Safe,, Accurate,, Visit, the, IRS, Website, 800-50-0733, OMB, No., 1545-0008, FAST!, Use, use, ~, file, at, www.irs, goviefile, b, Employer, identificatio...
61     [you, are, 800-50-0733, OMB, No., 1545-0008, on, required, to, file, a, tax, return,, a, negligence, penalty, or, other, sanction, may, be, imposed, you, if, this, income, is, taxable, and, you, f...
62     [04-2068096, This, Visit, the, IRS, Website, Safe,, Accurate,, me, ~, file, at, www.irs, gov.efile., FAST!, Use, 2, Federal, income, tax, withheld, OMB, No., 1545-0008, 47320, ., 49, a, Employee's...
63     [066-13-5202, FAST, Use, 24-8916953, 57571.49, 8139.51, Reed,, Jefferson, and, Beasley, LLC, 62460.82, 4778.25, 263, Reyes, Gardens, Suite, 869, 67624.89, 1961.12, Brownfort, 72120-4069, 62460.82,...
64     [a, Employee's, social, security, number, Safe,, Accurate., Visit, the, IRS, Website, 166-17-3465, Re, ~, file, OMB, No., 1545-0008, FAST!, Us, at, www.irs.gov/efile., b, Employer, identification,...
65     [0'00684, 23056.07, Corp, 30-5492273, W-2, 2018, W-2, and, EARNINGS, SUMMARY, ADP, Employee, Reference, Copy, his, blue, Earnings, Summary, section, is, included, with, your, W-2, to, help, descri...
66     [security, tax, with, hel, Social, security, wa, Social, security, tax, withheld, Social, security, wag, Social, security, tax, withheld, 142035, .23, 142035.23, Medicare, tax, 10865, withheld, 32...
67     [Wages,, tips,, other, comp., 2, Federal, income, tax, withheld, 174110., 95, 59784, ., 88, 3, Social, security, wages, 4, Social, security, tax, withheld, 169581, ., 52, 12972, ., 99, 5, Medicare...
68     [Jackson, Service., Apt., report, number, and, b, Employer, identification, number, (EIN), Employee's, social, security, number, 72-7975122, 117-65-3078, C, Employer's, name,, address,, and, ZIP, ...
69     [identification, number, 72-7975122, 117-65-3078, Employer's, name,, address,, and, ZIP, code, Ford,, Sanders, a, d, Lawrence, Ltd, OMB, No., 1545-0008, This, information, is, being, 304, a, on, M...
70     [a, Employee's, social, security, number, Safe,, Accurate,, we, file, Visit, the, IRS, Website, 024-25-1828, OMB, No., 1545-0008, FAST!, Use, at, www.irs, govefile, b, Employer, identification, nu...
71     [employer., (C-Box, Information,, withheld, box, 2018, Employee, Reference, W-2, Wage, and, Tax, Copy, 2018, W-2, and, EARNINGS, SUMMARY, Stateme, Copy, C, for, employee's, This, blue, Earnings, S...
72     [other, comp, ., 21Employer's, name, ,, address, ,, and, withheld, 16117, .02, 2, Federal, income, tax, w, d, al, security, 64222.03, Johnston, LLC, dress,, Itd, and, ZIP, code, Employer, use, onl...
73     [Wages,, tips,, other, comp., 2, Federal, income, tax, withheld, 97553, ., 19, 28985.52, 3, Social, security, wages, 4, Social, security, tax, withheld, 30331, ., 85, 6145., 39, 5, Medicare, wages...
74     [645, 2018, W-2, and, EARNINGS, SUMMARY, ADP, Employee, Reference, Copy, his, blue, Earnings, Summary, section, is, included, with, your, W-2, to, help, describe, portions, in, more, detail., Wage...
75     [37, withheld, 75978., wages, Medicare, 68, and, tips, 5812, Medicare, tax, .37, withheld, "gayanes, and, tips, Control, number, Dept., Corp, ., Employer, use, only, Dept., Corp, ., Employer, use,...
76     [1, Wages,, tips,, other, comp., 2, Federal, income, tax, withheld, 100685.61, 15340.3, 3, Social, security, wages, 4, Social, security, tax, withheld, 104087.79, 7962.72, 5, Medicare, wages, and,...
77     [a, Employee's, social, security, number, Safe,, Accurate,, Visit, the, IRS, Website, 537-16-0400, OMB, No., 1545-0008, FAST!, Use, "se, ~, file, at, www.irs.gov/efile., b, Employer, identificatio...
78     [the, Internal, Revenue, Service., If, you, are, 537-16-0400, OMB, No., 1545-0008, on, required, to, file, a, tax, return,, a, negligence, penalty, or, other, sanction, may, be, imposed, you, if, ...
79     [114952, Wages,, tips,, other, comp., Federal, income, tax, withheld, 242842, ., 12, 39092, ., 15, 3, Social, security, wages, 4, Social, security, tax, withheld, 265916., 06, 20419, ., 08, 5, Med...
80     [This, sanction, 71172, number, etc., a, Employee's, social, security, b, e, b, Employer, identification, number, (EIN), 16-3723191, 372-90-4537, c, Employer's, name,, address,, and, ZIP, code, OM...
81     [records., Employer, identification, number, 16-3723191, 372-90-4537, Employer's, name,, address,, and, ZIP, code, OMB, No., 1545-0008, required, This, to, information, file, a, tax, is, return,, ...
82     [a, Employee's, social, security, number, Safe,, Accurate,, Visit, the, IRS, Website, 753-52-7353, OMB, No., 1545-0008, FAST!, Use, e, file, at, www.irs.gov/efile., b, Employer, identification, nu...
83     [Service., If, you, are, 753-52-7353, OMB, No., 1545-0008, on, required, to, file, a, tax, return,, a, negligence, penalty, or, other, sanction, may, be, imposed, you, if, this, income, is, taxabl...
84     [This, Greas, re, detail, portions, 2018, W-2, and, EARNINGS, SUMMARY, is, blue, Earnings, Summary, section, included, with, your, W-2, to, help, dese, The, reverse, side, includes, general, infor...
85     [penalty, sanction, Employer's, etc., 319382.35, Notice, a, Employee's, social, security, number, b, Employer, identification, number, (EIN), 741-51-3041, 37-8013701, OMB, No., 1545-0008, Safe,, A...
86     [security, number, b, Employer, identification, number, 741-51-3041, This, information, to, file, a, is, tax, being, furnished, to, the, Internal, a, or, Revenue, other, Service., on, If, may, you...
87     [1, Wages,, tips,, other, comp., 2, Federal, income, tax, withheld, 131815.8, 27993.41, 3, Social, security, wages, 4, Social, security, tax, withheld, 131475.37, 10057.87, 5, Medicare, wages, and...
88     [12a, decal, tax, 47576.87, withheld, Wages,, 192428.9, tips,, other, comp, Social, security, tax, withheld, 7345.61, Social, 94202.47, security, wages, dicare, tax, withheld, 4161.76, Medicare, w...
89     [Earnings, This, 200804.23, 152880.37, Profile., Stokes, withheld, 12a, 126, Locality, Fort, Tax, ADP, 2018, W-2, and, EARNINGS, SUMMARY, is, blue, a, in, Summary, section, included, with, your, W...
90     [Dept., :, Federal, income, tax, withheld, 37298.89, Medicare, tax, withheld, 7, 6, d, Control, 35, 1, Wages,, tips., mer, Social, security, 10624.97, tax, withheld, Medicare, wages, an, Employer,...
91     [a, Employee's, social, security, number, Safe,, Accurate., Visit, the, IRS, Website, Re, ~, file, 133-91-4942, OMB, No., 1545-0008, FAST!, US, at, www.irs.gov/efile., b, Employer, identification,...
92     [231000.89, identificati, Jonathan, Jeffreyberg, 133, number, a, Employee's, social, security, num, b, e, b, Employer, identification, number, (EIN), 80-1366099, 595-45-6525, c, Employer's, name,,...
93     [d, f, c, a, a, Employee's, social, security, number, 80-1366099, 595-45-6525, Employer's, name,, address,, and, ZIP, code, OMB, No., 1545-0008, This, information, is, being, f, Bell,, Ortiz, and,...
94     [12a, 2, Federal, income, tax, withheld, 52569.93, 1, Wages,, 147123.33, tips,, other, comp., 4, Social, security, 9015, tax, withheld, ., 83, 3, Social, 117853.94, security, wages, 6, Medicare, t...
95     [1, 26814, Wages,, tips,, other, comp., 2, Federal, income, tax, withheld, 72866., 96, 17704, .07, 3, Social, security, wages, 4, Social, security, tax, withheld, 76981, ., 85, 5889, ., 11, 5, Med...

In [24]:
# Tokenize the train and validation data and convert them to pandas dataframes
train = tokenize_data(train_data)
val = tokenize_data(val_data)

  0%|          | 0/844 [00:00<?, ?ex/s]

  0%|          | 0/284 [00:00<?, ?ex/s]

In [25]:
train.head()

,transcript,ner_tags,input_ids,attention_mask
0,"[(C-Box, Profile., Information,, Medicare, :46, 88415, Employer's, 1653.98, Employee, Reference, W-2, Wage, !, ), and, Tax, Copy, 2018, W-2, and, EARNINGS, SUMMARY, Stateme, Copy, C, for, employee...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[101, 1006, 1039, 1011, 3482, 6337, 1012, 2592, 1010, 27615, 1024, 4805, 6070, 23632, 2629, 11194, 1005, 1055, 29309, 1012, 5818, 7904, 4431, 1059, 1011, 1016, 11897, 999, 1007, 1998, 4171, 6100, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,"[Dept., 2, Federal, income, tax, withheld, Employer's, name,, address, ,, and, ZIP, code, security, wages, Lopez-Daniel, PLC, Employer, use, only, Medicare, wages, and, 4, Social, security, tax, w...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[101, 29466, 1012, 1016, 2976, 3318, 4171, 2007, 24850, 11194, 1005, 1055, 2171, 1010, 4769, 1010, 1998, 14101, 3642, 3036, 12678, 8685, 1011, 3817, 15492, 11194, 2224, 2069, 27615, 12678, 1998, 1...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,"[Wages,, tips,, other, comp., 2, Federal, income, tax, withheld, 240330, ., 89, 35494, ., 65, 3, Social, security, wages, 4, Social, security, tax, withheld, 280634.5, 21468, .54, 5, Medicare, wag...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 9, 9, 10, 10, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 12, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, ...","[101, 12678, 1010, 10247, 1010, 2060, 4012, 2361, 1012, 1016, 2976, 3318, 4171, 2007, 24850, 11212, 22394, 2692, 1012, 6486, 27878, 2683, 2549, 1012, 3515, 1017, 2591, 3036, 12678, 1018, 2591, 303...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,"[1, Wages,, tips,, other, comp., 2, Federal, income, tax, withheld, 233146.9, 73449.38, 3, Social, security, wages, 4, Social, security, tax, withheld, 208770.54, 15970.95, 5, Medicare, wages, and...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 4, ...","[101, 1015, 12678, 1010, 10247, 1010, 2060, 4012, 2361, 1012, 1016, 2976, 3318, 4171, 2007, 24850, 22115, 16932, 2575, 1012, 1023, 6421, 22932, 2683, 1012, 4229, 1017, 2591, 3036, 12678, 1018, 259...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4,"[23593.7, 18732.51, 245653.79, name,, address,, W-2, 2018, W-2, and, EARNINGS, SUMMARY, ADP, Employee, Reference, Copy, his, blue, Earnings, Summary, section, is, included, with, your, W-2, to, he...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[101, 17825, 2683, 2509, 1012, 1021, 7612, 2475, 1012, 4868, 21005, 26187, 2509, 1012, 6535, 2171, 1010, 4769, 1010, 1059, 1011, 1016, 2760, 1059, 1011, 1016, 1998, 16565, 12654, 4748, 2361, 7904,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [26]:
# Define a function to create ner tags for each token in a given transcript and ner tags list
def create_ner_tags(tokens, ner_tags):
    # Preprocess the tokens using the tokenizer
    preprocessed_tokens = tokenizer(tokens, is_split_into_words=True, truncation=True)
    # Get the input ids and word ids from the preprocessed tokens
    input_ids = preprocessed_tokens['input_ids']
    word_ids = preprocessed_tokens.word_ids()
    
    # Create an empty list for storing the ner tags for each token
    ner_tags_for_tokens = []
    # Loop through each token id in the input ids list
    for ind, token in enumerate(input_ids):
        # If the word id is None, append -100 to the ner tags list (this means that this token will be ignored for loss calculation)
        if word_ids[ind] == None:
            ner_tags_for_tokens.append(-100)
        # If the word id is equal to the previous word id, append -100 to the ner tags list (this means that this token is part of a subword and will be ignored for loss calculation)
        elif word_ids[ind] == word_ids[ind - 1]:
            ner_tags_for_tokens.append(-100)
        # Otherwise, append the corresponding ner tag from the ner tags list (this means that this token is a whole word and will be used for loss calculation)
        else:
            ner_tags_for_tokens.append(ner_tags[word_ids[ind]])
    # Return the ner tags for tokens list
    return ner_tags_for_tokens

In [27]:
# Create ner tags for each token in the example transcript and ner tags list
tags = create_ner_tags(example_1, ner)

In [28]:
# Loop through each token id and the corresponding ner tag in the input ids and tags lists
for ind, tok in enumerate(tokenizer.convert_ids_to_tokens(tokens['input_ids'])):
    print(tok, tags[ind])

[CLS] -100
( 0
c -100
- -100
box -100
profile 0
. -100
information 0
, -100
medicare 0
: 0
46 -100
88 0
##41 -100
##5 -100
employer 0
' -100
s -100
1653 0
. -100
98 -100
employee 0
reference 0
w 0
- -100
2 -100
wage 0
! 0
) 0
and 0
tax 0
copy 0
2018 0
w 0
- -100
2 -100
and 0
earnings 0
summary 0
state 0
##me -100
copy 0
c 0
for 0
employee 0
' -100
s -100
d 0
control 0
number 0
dept 0
. -100
corp 0
. -100
this 0
blue 0
earnings 0
summary 0
section 0
is 0
included 0
with 0
your 0
w 0
- -100
2 -100
to 0
help 0
describe 0
portions 0
in 0
more 0
detail 0
2018 15
the 0
reverse 0
side 0
includes 0
general 0
information 0
that 0
you 0
may 0
also 0
find 0
helpful 0
. -100
dept 0
150 0
om 0
##b -100
no 0
. -100
154 0
##5 -100
- -100
000 -100
##8 -100
employer 0
' -100
s -100
name 0
, -100
address 0
, -100
and 0
zip 0
code 0
employer 0
use 0
only 0
lopez 1
- -100
daniel -100
plc 1
ad 0
##p -100
1 0
. -100
the 0
following 0
information 0
reflects 0
your 0
final 0
2018 0
pay 0
stu 0
##b -100
plus 0
any 0
adjustments 0
submitted 0
by 0
your 0
employer 0
. -100
470 2
##7 -100
##6 -100
jonathan 2
mountain 2
west 3
pamela 3
de 4
88 5
##41 -100
##5 -100
- 5
09 5
##8 -100
##1 -100
gross 0
pay 0
101 0
##27 -100
##7 -100
5 0
social 0
security 0
78 0
##7 -100
##7 -100
4 0
6 0
fed 0
. -100
income 0
box 0
4 0
of 0
w 0
##j -100
elf 0
employees 0
name 0
, -100
address 0
and 0
batch 0
zip 0
code 0
127 0
##16 -100
. -100
67 -100
w 0
##v -100
. -100
state 0
income 0
tax 0
# 0
02 -100
##0 -100
##21 -100
box 0
tax 0
2 0
with 0
##held -100
of 0
w 0
- 0
2 0
medicare 0
tax 0
box 0
17 0
of 0
w 0
. -100
2 -100
1653 0
98 0
lauren 7
vance 7
with 0
##held -100
210 0
##0 -100
. -100
8 -100
box 0
19 0
of 0
w 0
- -100
2 0
131 0
##42 -100
. -100
9 -100
131 0
##33 -100
green 0
common 0
suite 0
03 0
##2 -100
box 0
6 13
of 0
w 0
. -100
2 -100
parker 0
##stad -100
ky 0
sui 0
/ -100
sd 0
##i -100
/ -100
fl -100
##i -100
108 0
##80 -100
- -100
48 -100
##90 -100
box 0
14 0
of 0
w 0
. -100
2 -100
2 0
. -100
your 0
gross 0
pay 0
was 0
adjusted 0
as 0
follows 0
to 0
produce 0
your 0
w 0
- -100
2 -100
statement 0
. -100
b 0
employer 0
' -100
s -100
fed 0
id 0
number 0
37 6
- -100
95 -100
##20 -100
##49 -100
##7 -100
ja 0
employee 0
' -100
s -100
ss 0
##a -100
number 0
80 9
##gg -100
tips 9
, -100
other 0
com 0
##p -100
. -100
3 0
social 0
security 0
wages 0
2 0
federal 0
income 0
81 8
##1 -100
- -100
27 -100
- -100
08 -100
##25 -100
tax 0
with 0
##held -100
wages 0
, -100
tips 0
, -100
other 0
compensation 0
box 0
of 0
##way -100
social 0
sec 0
##ui -100
medical 0
4 0
social 0
security 0
tax 0
with 0
##held -100
plus 0
gt 0
##l -100
box 0
box 0
wages 0
3 0
of 0
w 0
. 0
2 0
wages 0
box 0
5 0
of 0
w 0
. 0
2 0
tips 0
, -100
w 0
##v -100
. -100
state -100
etc 0
. -100
wages 0
, -100
dar 0
##in -100
points 0
5 0
medicare 0
wages 0
and 0
tips 0
es 0
##s -100
401 0
( -100
k -100
) -100
( 0
d -100
- -100
box -100
121 0
2 0
) -100
box 0
16 0
of 0
w 0
. -100
2 -100
72 0
##44 -100
##1 -100
. -100
52 0
medicare 0
tax 0
with 0
##held -100
reported 0
w 0
- -100
2 -100
wages 0
74 0
##54 -100
101 0
##27 -100
##7 -100
. -100
45 -100
social 0
security 0
tips 0
127 0
##16 -100
. 0
67 -100
101 0
##27 -100
##7 -100
74 0
##54 -100
b 0
18 0
of 0
w 0
##2 -100
102 0
##9 -100
##7 -100
##3 -100
. -100
33 -100
8 0
allocated 0
210 0
##0 -100
tips 0
. 0
8 -100
127 0
16 0
. -100
67 -100
ma 0
74 0
##54 -100
##5 -100
9 0
verification 0
code 0
3 0
. -100
employee 0
w 0
- -100
4 -100
profile 0
. 0
to 0
change 0
your 0
employee 0
80 0
##6 -100
##8 -100
##3 -100
. -100
32 -100
127 0
##16 -100
. -100
67 -100
for 0
a 0
, 0
w 0
- -100
4 -100
file 0
101 0
##24 -100
##7 -100
5 0
with 0
your 0
payroll 0
dept 0
. -100
68 0
##9 -100
( 0
45 -100
##4 -100
new 0
w 0
- -100
[SEP] -100

## Creating ner preprocesssed column

In [29]:
%%time
# Measure the execution time of creating ner tags for the train and validation data
train['ner_tags'] = train_data.apply(lambda x: create_ner_tags(x['transcript'], x['ner_tags']), axis=1)

CPU times: user 2.15 s, sys: 1.14 ms, total: 2.15 s
Wall time: 2.15 s

In [30]:
# Apply the create_ner_tags function to the validation data and store the result as a new column
val['ner_tags'] = val_data.apply(lambda x: create_ner_tags(x['transcript'], x['ner_tags']), axis=1)

In [31]:
# Drop the transcript column from the train and validation data
train.drop('transcript', axis=1, inplace=True)
val.drop('transcript', axis=1, inplace=True)

In [32]:
# Convert the train and validation data to Dataset objects from the datasets library
train = Dataset.from_pandas(train)
train = train.rename_column("ner_tags", "labels")
# Rename the ner_tags column to labels in both datasets
val = Dataset.from_pandas(val)
val = val.rename_column("ner_tags", "labels")

In [33]:
# Set the format of both datasets to torch
train.set_format('torch')
val.set_format('torch')

In [34]:
train

Dataset({
    features: ['labels', 'input_ids', 'attention_mask'],
    num_rows: 844
})

In [35]:
# Import the DataCollatorForTokenClassification class from the transformers library
from transformers import DataCollatorForTokenClassification
# Create a data collator object using the tokenizer
data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [36]:
!pip install evaluate seqeval

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Collecting evaluate
  Downloading evaluate-0.4.0-py3-none-any.whl (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.4/81.4 kB 5.9 MB/s eta 0:00:00
Collecting seqeval
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 4.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... - done
Requirement already satisfied: datasets>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from evaluate) (2.1.0)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.10/site-packages (from evaluate) (1.23.5)
Requirement already satisfied: dill in /opt/conda/lib/python3.10/site-packages (from evaluate) (0.3.7)
Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (from evaluate) (2.0.2)
Requirement already satisfied: requests>=2.19.0 in /opt/conda/lib/python3.10/site-packages (from evaluate) (2.31.0)
Requirement already satisfied: tqdm>=4.62.1 in /opt/conda/lib/python3.10/site-packages (from evaluate) (4.66.1)
Requirement already satisfied: xxhash in /opt/conda/lib/python3.10/site-packages (from evaluate) (3.3.0)
Requirement already satisfied: multiprocess in /opt/conda/lib/python3.10/site-packages (from evaluate) (0.70.15)
Requirement already satisfied: fsspec[http]>=2021.05.0 in /opt/conda/lib/python3.10/site-packages (from evaluate) (2023.9.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /opt/conda/lib/python3.10/site-packages (from evaluate) (0.16.4)
Requirement already satisfied: packaging in /opt/conda/lib/python3.10/site-packages (from evaluate) (21.3)
Requirement already satisfied: responses<0.19 in /opt/conda/lib/python3.10/site-packages (from evaluate) (0.18.0)
Requirement already satisfied: scikit-learn>=0.21.3 in /opt/conda/lib/python3.10/site-packages (from seqeval) (1.2.2)
Requirement already satisfied: pyarrow>=5.0.0 in /opt/conda/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (11.0.0)
Requirement already satisfied: aiohttp in /opt/conda/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (3.8.4)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from huggingface-hub>=0.7.0->evaluate) (3.12.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub>=0.7.0->evaluate) (6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub>=0.7.0->evaluate) (4.6.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.10/site-packages (from packaging->evaluate) (3.0.9)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests>=2.19.0->evaluate) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests>=2.19.0->evaluate) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests>=2.19.0->evaluate) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests>=2.19.0->evaluate) (2023.7.22)
Requirement already satisfied: scipy>=1.3.2 in /opt/conda/lib/python3.10/site-packages (from scikit-learn>=0.21.3->seqeval) (1.11.2)
Requirement already satisfied: joblib>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from scikit-learn>=0.21.3->seqeval) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from scikit-learn>=0.21.3->seqeval) (3.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas->evaluate) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas->evaluate) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.10/site-packages (from pandas->evaluate) (2023.3)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.16.0)
Building wheels for collected packages: seqeval
  Building wheel for seqeval (setup.py) ... - \ done
  Created wheel for seqeval: filename=seqeval-1.2.2-py3-none-any.whl size=16165 sha256=78e927a5328844f8428d40b7a05ea65fe4dacae753e8c4910fd649c43fbdedfb
  Stored in directory: /root/.cache/pip/wheels/1a/67/4a/ad4082dd7dfc30f2abfe4d80a2ed5926a506eb8a972b4767fa
Successfully built seqeval
Installing collected packages: seqeval, evaluate
Successfully installed evaluate-0.4.0 seqeval-1.2.2

In [37]:
# Load the seqeval evaluation metric from the evaluate module
import evaluate

seqeval = evaluate.load("seqeval")

Downloading builder script:   0%|          | 0.00/6.34k [00:00<?, ?B/s]

In [38]:
# Import the load_metric function from the datasets library
from datasets import load_metric
metric = load_metric("seqeval")

Downloading builder script:   0%|          | 0.00/2.47k [00:00<?, ?B/s]

In [39]:
# labels = [ner_labels[i] for i in train["ner_tags"]]
# metric.compute(predictions=[labels], references=[labels])

In [40]:
ner_labels_dict

{'OTHER': 0,
 'employerName': 1,
 'employerAddressStreet_name': 2,
 'employerAddressCity': 3,
 'employerAddressState': 4,
 'employerAddressZip': 5,
 'einEmployerIdentificationNumber': 6,
 'employeeName': 7,
 'ssnOfEmployee': 8,
 'box1WagesTipsAndOtherCompensations': 9,
 'box2FederalIncomeTaxWithheld': 10,
 'box3SocialSecurityWages': 11,
 'box4SocialSecurityTaxWithheld': 12,
 'box16StateWagesTips': 13,
 'box17StateIncomeTax': 14,
 'taxYear': 15}

In [41]:
# Get a list of ner labels from the dictionary keys
list(ner_labels.keys())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [42]:
# Define a dictionary of id to label mapping for each numeric code
id2label = {
    0 : "OTHER",
    1 : "employerName",
    2 : "employerAddressStreet_name",
    3 : "employerAddressCity",
    4 : "employerAddressState",
    5 : "employerAddressZip",
    6 : "einEmployerIdentificationNumber",
    7 : "employeeName",
    8 : "ssnOfEmployee",
    9 : "box1WagesTipsAndOtherCompensations",
    10 : "box2FederalIncomeTaxWithheld",
    11 : "box3SocialSecurityWages",
    12 : "box4SocialSecurityTaxWithheld",
    13 : "box16StateWagesTips",
    14 : "box17StateIncomeTax",
    15 : "taxYear"
}
# Define a dictionary of label to id mapping for each ner label
label2id = {
    'OTHER': 0,
     'employerName': 1,
     'employerAddressStreet_name': 2,
     'employerAddressCity': 3,
     'employerAddressState': 4,
     'employerAddressZip': 5,
     'einEmployerIdentificationNumber': 6,
     'employeeName': 7,
     'ssnOfEmployee': 8,
     'box1WagesTipsAndOtherCompensations': 9,
     'box2FederalIncomeTaxWithheld': 10,
     'box3SocialSecurityWages': 11,
     'box4SocialSecurityTaxWithheld': 12,
     'box16StateWagesTips': 13,
     'box17StateIncomeTax': 14,
     'taxYear': 15
}

# <span style="font-family:cursive;text-align:center">⬇️ Training</span>

In [43]:
# Import the AutoModelForTokenClassification class from the transformers library
from transformers import AutoModelForTokenClassification, TrainingArguments, Trainer
# Load a model for token classification from a pretrained model name, specifying the number of labels and the id2label and label2id dictionaries
model = AutoModelForTokenClassification.from_pretrained(
    "distilbert-base-uncased", num_labels=16, id2label=id2label, label2id=label2id
)

Downloading model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [44]:
# Move the model to the device (cuda or cpu)
model.to(device)

DistilBertForTokenClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): MultiHeadSelfAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=16, bias=True)
)

In [45]:
# Create a training arguments object with various hyperparameters and settings for training and evaluation
training_args = TrainingArguments(
    output_dir="/kaggle/working/",
    learning_rate=2e-5,
    logging_strategy = 'epoch',
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=20,
    weight_decay=0.01,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    report_to = 'none'
)

In [46]:
# Create a trainer object with the model, the training arguments, the train and validation datasets, the tokenizer, the data collator, and the metric
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train,
    eval_dataset=val,
    tokenizer=tokenizer,
    data_collator=data_collator,
#     compute_metrics=metric,
)

In [47]:
# Train the model using the trainer object
trainer.train()

You're using a DistilBertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

TrainOutput(global_step=1060, training_loss=0.07571141584864202, metrics={'train_runtime': 555.8961, 'train_samples_per_second': 30.365, 'train_steps_per_second': 1.907, 'total_flos': 2200921577092224.0, 'train_loss': 0.07571141584864202, 'epoch': 20.0})

# <span style="font-family:cursive;text-align:center">⬇️ Inference</span>

In [48]:
from transformers import pipeline
# Create a classifier object using the ner pipeline, the trained model, the tokenizer, and the device
classifier = pipeline("ner", model=model, tokenizer=tokenizer, device=device)
# Set the tokenizer attribute is_split_into_words to True (this means that the input is already split into words)
classifier.tokenizer.is_split_into_words = True

In [49]:
# Apply the classifier to a list of words
tokens = classifier(["77796.34", "3759.51" ,"withheby" ,"2018", "W-2", "and" ,"EARNINGS", "SUMMARY", "ADP", "Employee"])
# Create an empty list for storing the labels
labels = []
# Loop through each element in the tokens list
for li in tokens:
    # Loop through each dictionary in the element
    for dic in li:
        # Append the entity value from the dictionary to the labels list
        labels.append(dic['entity'])

In [50]:
labels

['box3SocialSecurityWages',
 'box3SocialSecurityWages',
 'box3SocialSecurityWages',
 'box3SocialSecurityWages',
 'box3SocialSecurityWages',
 'box3SocialSecurityWages',
 'box4SocialSecurityTaxWithheld',
 'box3SocialSecurityWages',
 'box3SocialSecurityWages',
 'box4SocialSecurityTaxWithheld',
 'OTHER',
 'employerAddressCity',
 'OTHER',
 'taxYear',
 'OTHER',
 'OTHER',
 'OTHER',
 'OTHER',
 'OTHER',
 'OTHER',
 'OTHER',
 'OTHER',
 'OTHER']

In [51]:
tokens

[[{'entity': 'box3SocialSecurityWages',
   'score': 0.34892526,
   'index': 1,
   'word': '77',
   'start': 0,
   'end': 2},
  {'entity': 'box3SocialSecurityWages',
   'score': 0.5969268,
   'index': 2,
   'word': '##7',
   'start': 2,
   'end': 3},
  {'entity': 'box3SocialSecurityWages',
   'score': 0.5498678,
   'index': 3,
   'word': '##9',
   'start': 3,
   'end': 4},
  {'entity': 'box3SocialSecurityWages',
   'score': 0.6177936,
   'index': 4,
   'word': '##6',
   'start': 4,
   'end': 5},
  {'entity': 'box3SocialSecurityWages',
   'score': 0.5117226,
   'index': 5,
   'word': '.',
   'start': 5,
   'end': 6},
  {'entity': 'box3SocialSecurityWages',
   'score': 0.4532416,
   'index': 6,
   'word': '34',
   'start': 6,
   'end': 8}],
 [{'entity': 'box4SocialSecurityTaxWithheld',
   'score': 0.2601858,
   'index': 1,
   'word': '375',
   'start': 0,
   'end': 3},
  {'entity': 'box3SocialSecurityWages',
   'score': 0.469249,
   'index': 2,
   'word': '##9',
   'start': 3,
   'end': 4},
  {'entity': 'box3SocialSecurityWages',
   'score': 0.36161128,
   'index': 3,
   'word': '.',
   'start': 4,
   'end': 5},
  {'entity': 'box4SocialSecurityTaxWithheld',
   'score': 0.27149677,
   'index': 4,
   'word': '51',
   'start': 5,
   'end': 7}],
 [{'entity': 'OTHER',
   'score': 0.2556723,
   'index': 1,
   'word': 'with',
   'start': 0,
   'end': 4},
  {'entity': 'employerAddressCity',
   'score': 0.21930958,
   'index': 2,
   'word': '##he',
   'start': 4,
   'end': 6},
  {'entity': 'OTHER',
   'score': 0.26755506,
   'index': 3,
   'word': '##by',
   'start': 6,
   'end': 8}],
 [{'entity': 'taxYear',
   'score': 0.64886034,
   'index': 1,
   'word': '2018',
   'start': 0,
   'end': 4}],
 [{'entity': 'OTHER',
   'score': 0.6989769,
   'index': 1,
   'word': 'w',
   'start': 0,
   'end': 1},
  {'entity': 'OTHER',
   'score': 0.52215105,
   'index': 2,
   'word': '-',
   'start': 1,
   'end': 2},
  {'entity': 'OTHER',
   'score': 0.7732088,
   'index': 3,
   'word': '2',
   'start': 2,
   'end': 3}],
 [{'entity': 'OTHER',
   'score': 0.25566486,
   'index': 1,
   'word': 'and',
   'start': 0,
   'end': 3}],
 [{'entity': 'OTHER',
   'score': 0.8204052,
   'index': 1,
   'word': 'earnings',
   'start': 0,
   'end': 8}],
 [{'entity': 'OTHER',
   'score': 0.6944387,
   'index': 1,
   'word': 'summary',
   'start': 0,
   'end': 7}],
 [{'entity': 'OTHER',
   'score': 0.45854938,
   'index': 1,
   'word': 'ad',
   'start': 0,
   'end': 2},
  {'entity': 'OTHER',
   'score': 0.7194302,
   'index': 2,
   'word': '##p',
   'start': 2,
   'end': 3}],
 [{'entity': 'OTHER',
   'score': 0.6320117,
   'index': 1,
   'word': 'employee',
   'start': 0,
   'end': 8}]]

In [52]:
# Define a function to extract labels from inference output
def extract_labels_from_inference(opt):
    lab = []
    for li in opt:
        lab.append(li[0]['entity'])
    return lab

In [53]:
# Apply the function to the tokens list
extract_labels_from_inference(tokens)

['box3SocialSecurityWages',
 'box4SocialSecurityTaxWithheld',
 'OTHER',
 'taxYear',
 'OTHER',
 'OTHER',
 'OTHER',
 'OTHER',
 'OTHER',
 'OTHER']

In [54]:
words = "77796.34 3759.51 withheby 2018 W-2 and EARNINGS SUMMARY ADP Employee"
words = words.split()

In [55]:
len(words)

10

In [56]:
len(labels)

23

In [57]:
tokens

[[{'entity': 'box3SocialSecurityWages',
   'score': 0.34892526,
   'index': 1,
   'word': '77',
   'start': 0,
   'end': 2},
  {'entity': 'box3SocialSecurityWages',
   'score': 0.5969268,
   'index': 2,
   'word': '##7',
   'start': 2,
   'end': 3},
  {'entity': 'box3SocialSecurityWages',
   'score': 0.5498678,
   'index': 3,
   'word': '##9',
   'start': 3,
   'end': 4},
  {'entity': 'box3SocialSecurityWages',
   'score': 0.6177936,
   'index': 4,
   'word': '##6',
   'start': 4,
   'end': 5},
  {'entity': 'box3SocialSecurityWages',
   'score': 0.5117226,
   'index': 5,
   'word': '.',
   'start': 5,
   'end': 6},
  {'entity': 'box3SocialSecurityWages',
   'score': 0.4532416,
   'index': 6,
   'word': '34',
   'start': 6,
   'end': 8}],
 [{'entity': 'box4SocialSecurityTaxWithheld',
   'score': 0.2601858,
   'index': 1,
   'word': '375',
   'start': 0,
   'end': 3},
  {'entity': 'box3SocialSecurityWages',
   'score': 0.469249,
   'index': 2,
   'word': '##9',
   'start': 3,
   'end': 4},
  {'entity': 'box3SocialSecurityWages',
   'score': 0.36161128,
   'index': 3,
   'word': '.',
   'start': 4,
   'end': 5},
  {'entity': 'box4SocialSecurityTaxWithheld',
   'score': 0.27149677,
   'index': 4,
   'word': '51',
   'start': 5,
   'end': 7}],
 [{'entity': 'OTHER',
   'score': 0.2556723,
   'index': 1,
   'word': 'with',
   'start': 0,
   'end': 4},
  {'entity': 'employerAddressCity',
   'score': 0.21930958,
   'index': 2,
   'word': '##he',
   'start': 4,
   'end': 6},
  {'entity': 'OTHER',
   'score': 0.26755506,
   'index': 3,
   'word': '##by',
   'start': 6,
   'end': 8}],
 [{'entity': 'taxYear',
   'score': 0.64886034,
   'index': 1,
   'word': '2018',
   'start': 0,
   'end': 4}],
 [{'entity': 'OTHER',
   'score': 0.6989769,
   'index': 1,
   'word': 'w',
   'start': 0,
   'end': 1},
  {'entity': 'OTHER',
   'score': 0.52215105,
   'index': 2,
   'word': '-',
   'start': 1,
   'end': 2},
  {'entity': 'OTHER',
   'score': 0.7732088,
   'index': 3,
   'word': '2',
   'start': 2,
   'end': 3}],
 [{'entity': 'OTHER',
   'score': 0.25566486,
   'index': 1,
   'word': 'and',
   'start': 0,
   'end': 3}],
 [{'entity': 'OTHER',
   'score': 0.8204052,
   'index': 1,
   'word': 'earnings',
   'start': 0,
   'end': 8}],
 [{'entity': 'OTHER',
   'score': 0.6944387,
   'index': 1,
   'word': 'summary',
   'start': 0,
   'end': 7}],
 [{'entity': 'OTHER',
   'score': 0.45854938,
   'index': 1,
   'word': 'ad',
   'start': 0,
   'end': 2},
  {'entity': 'OTHER',
   'score': 0.7194302,
   'index': 2,
   'word': '##p',
   'start': 2,
   'end': 3}],
 [{'entity': 'OTHER',
   'score': 0.6320117,
   'index': 1,
   'word': 'employee',
   'start': 0,
   'end': 8}]]

In [58]:
# Preprocess the words using the tokenizer (without adding special tokens)
preprocessed_tokens = tokenizer(words, is_split_into_words=True, truncation=True, add_special_tokens = False)

In [59]:
preprocessed_tokens

{'input_ids': [6255, 2581, 2683, 2575, 1012, 4090, 18034, 2683, 1012, 4868, 2007, 5369, 3762, 2760, 1059, 1011, 1016, 1998, 16565, 12654, 4748, 2361, 7904], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

## Inference on val data

In [60]:
# Define a function to load validation data from a given path
def load_val_data(path):
    directory = path

    tsv_file = glob.glob(directory + '/*.tsv')

    data = pd.DataFrame(columns = ['transcript'])

    for filename in tsv_file:
        data_i = pd.read_csv(filename, header=None)
        data_i.columns = ['start_index', 'end_index', 'x_top_left', 'y_top_left', 'x_bottom_right', 'y_bottom_right', 'transcript']
        data_i.dropna(subset=['transcript'], inplace=True)
        
        transcript = data_i['transcript'].to_list()
        
        data.loc[len(data)] = [transcript]
        
    return data

In [61]:
# Load the validation data without labels from a given path
val_data_without_labels = load_val_data('/kaggle/input/demo-data/dataset/val/boxes_transcripts')

In [62]:
# Get the third transcript from the validation data without labels
tok = val_data_without_labels['transcript'][2]

In [63]:
tok, len(tok)

(['Information,',
  '2018AOP.',
  'ex',
  '224720.73',
  'Employee',
  'Reference',
  'W-2',
  'and',
  'Tax',
  '2018',
  'W-2',
  'and',
  'EARNINGS',
  'SUMMARY',
  '2018',
  'This',
  'blue',
  'Earnings',
  'Summary',
  'section',
  'is',
  'included',
  'with',
  'your',
  'W-2',
  'to',
  'help',
  'describe',
  'portions',
  'in',
  'more',
  'detail',
  '3374305',
  'The',
  'reverse',
  'side',
  'includes',
  'general',
  'information',
  'that',
  'you',
  'may',
  'also',
  'find',
  'helpful.',
  'DUMB',
  'Dis.',
  '1565-609',
  'Salazar-Nguyen',
  'Lit',
  'Employer',
  'use',
  'only',
  'guyen',
  '227',
  'Allison',
  'Skyway',
  'code',
  'Suite',
  '370',
  'ADP',
  '1.',
  'The',
  'following',
  'information',
  'reflects',
  'your',
  'final',
  '2',
  '1',
  'pay',
  'stub',
  'plus',
  'any',
  'adjustments',
  'submitted',
  'by',
  'your',
  'employer.',
  'North',
  'Stephen',
  'No',
  'Gross',
  'Pay',
  '80044-4080',
  '208',
  '542',
  '1',
  'Social',
  'Secu',
  'Fed.',
  'Incon',
  '15937',
  '39',
  'at',
  'Employ',
  'Batch',
  'Tax',
  'Winheld',
  '52491.90',
  'KS.',
  'State',
  'Income',
  'address',
  'and',
  'Zip',
  'code',
  '#02021',
  'Box',
  '2',
  'of',
  'W.2',
  'Box',
  '17',
  'of',
  'W.2',
  '65',
  '15',
  '30',
  'Mary',
  'Wallace',
  '6731.17',
  'Box',
  '19',
  'of',
  'W.2',
  '34847',
  '6',
  '08126',
  'Taylor',
  'Meadow',
  'Suite',
  '427',
  'Box',
  'forwa',
  'West',
  'Danielleland',
  'SUNSOUFLI',
  'NC',
  '60338-2088',
  'Box',
  '14',
  'of',
  'W.2',
  '2.',
  'Your',
  'Gross',
  'Pay',
  'was',
  'adjusted',
  'as',
  'follows',
  'to',
  'produce',
  'your',
  'W-2',
  'Statement.',
  "Employer's",
  'FED',
  'ID',
  'number',
  "Employee's",
  '554',
  '215713',
  'comp.',
  '719-60-4085',
  'Wages.',
  'Tips,',
  'ce',
  'Social',
  'security',
  'wages',
  '209231.92',
  'Box',
  '1',
  'of',
  'wa',
  'Social',
  'Secu',
  'Medicare',
  'Tiny',
  'tax',
  'wit',
  'held',
  'Box',
  '3',
  'of',
  'W',
  '3',
  'Box',
  '5',
  'of',
  'W/',
  '2',
  'KS.',
  'State',
  'Wages.',
  'looka',
  'Plain',
  'Medicare',
  'wages',
  'and',
  'tips',
  'Less',
  '40109',
  '10',
  '84',
  '20',
  '232103.37',
  'Less',
  'Other',
  'Cafe',
  '125',
  '1264',
  '208',
  '142',
  '08',
  'Box',
  '16',
  'of',
  'W',
  '2',
  'Social',
  'security',
  'tips',
  'edicare',
  'tax',
  'withheld',
  'Box',
  '18',
  'of',
  '12',
  '208321',
  '.',
  '92',
  '6731.17',
  '208142.1',
  '9',
  'Verification',
  'Code',
  'Bocaned',
  'Sips',
  '232109.37',
  '3.',
  'Employee',
  'W-4',
  'Profile.',
  'To',
  'change',
  'your',
  'Employee',
  '219712',
  'W-4',
  '71',
  'Profile',
  'for',
  'm',
  'a',
  'file',
  'new',
  'W-4',
  'with',
  'your',
  'payroll',
  'dept.',
  '19',
  'N',
  'qualified',
  'plans',
  '224',
  '14',
  'Other',
  'structicon',
  'for',
  'box',
  '12',
  'Mary',
  'Wallace',
  '08126',
  'Taylor',
  'Meadow',
  'Suite',
  '427',
  'North',
  'Stephen',
  'MO',
  'Taxable',
  'Mortal',
  'S',
  '15',
  'State',
  'Alowances',
  "moyers'",
  'state',
  'D',
  'no.',
  '745-94-439',
  '17',
  'State',
  'inco',
  'STATE:',
  '6535.39',
  '142808.',
  'etc.',
  '62',
  '19',
  'Local',
  'income',
  'tax',
  'Local',
  'wages,',
  'tips,',
  'Locality',
  'name',
  'Wages,',
  'tips,',
  'other',
  '.',
  '2018',
  'LLC',
  'Social',
  'sexy',
  'me',
  'tax',
  'win',
  '209331',
  '-92',
  'ledicare',
  'wages',
  'and',
  'Ups',
  'Wages,',
  'tips',
  'ce',
  '15937',
  '.39',
  '2374305',
  '6731-37',
  "player's",
  'name,',
  'addrem',
  'Salazar-Nguyen',
  'Lit',
  '227',
  'Allison',
  'Skyway',
  'Suite',
  'Wages.',
  'tips.',
  'ce',
  'North',
  'Stephen',
  '10',
  'Federal',
  'income',
  'tax',
  'wig',
  '80048',
  '-40',
  'Salazar-Nguyen',
  'LLC',
  '208331.',
  '92',
  "Employer's",
  'FLD',
  'ID',
  'number',
  'care',
  'wages',
  'and',
  'tips',
  'Social',
  'security',
  'lax',
  'miss',
  '227',
  'Allison',
  'Skyway',
  'Suite',
  '370',
  '232109.37',
  'North',
  'Stephen',
  'gol',
  'member',
  'are',
  'tax',
  '15937.39',
  'wins',
  'ocial',
  'secur',
  '927',
  '208329',
  '6731.17',
  '19044-4080',
  'Employer',
  'use',
  'only',
  'Verification',
  'Code',
  "Employer's",
  'FED',
  'ID',
  'number',
  '73-9690828',
  '227',
  'Allison',
  'x',
  "Employee's",
  'Sy',
  'forth',
  'stephe',
  'Suite',
  '370',
  '224',
  'suified',
  'plans',
  'Allocated',
  'ups',
  '89044-4080',
  '14',
  'Other',
  '232109.37',
  "Employer's",
  'FED',
  'ID',
  'number',
  '73-9690929',
  'Social',
  'security',
  "Employee's",
  'SSA',
  '208231.32',
  'Allocated',
  'ops',
  'adress',
  'and',
  'Zip',
  'code',
  'Verification',
  'Code',
  '232309.37',
  'Mary',
  'Wallace',
  'Noequalised',
  'sdent',
  'care',
  'bene',
  '08126',
  'Taylor',
  'Meadow',
  'Suite',
  '427',
  '224',
  'West',
  'Danielleland',
  '20',
  'See',
  'imenactions',
  '260',
  'or',
  'box',
  '12',
  '15',
  '5',
  '60338-2088',
  '08126',
  'Taylor',
  'Meadow',
  "suite'",
  '427',
  'z',
  'es-54-415ma.',
  '16',
  'State',
  'wa',
  'West',
  'Danielleland',
  'NC',
  '6513gee',
  'lax',
  '18',
  'Local',
  'wages,',
  'tips,',
  '132809.',
  'ese.',
  '62',
  'bekess',
  'and',
  'Zip',
  'code',
  '60338#2088',
  'Mary',
  'wallace',
  '224720.73',
  'es...',
  '16',
  'State',
  'wages,',
  'tips,',
  'etc.',
  '08126',
  'ZAY289',
  'Locality',
  'name',
  'west',
  'Danielle',
  'Land',
  'Suite',
  '427',
  'Federal',
  'Montes',
  'Plasas',
  '18',
  'Local',
  'wages,',
  'ups,',
  'etc.',
  'W-2',
  'Wage',
  'and',
  '19',
  'Local',
  'income',
  '60338-2088',
  'Tax',
  'Copy',
  '34842.57',
  '2',
  '20',
  'Copy',
  'B',
  'to',
  'be',
  'filed',
  'with',
  "employee's",
  'Feder',
  'Locality',
  'nam',
  '2018',
  'Federal',
  'Income',
  'Tax',
  'Reforms',
  'On3',
  '1as',
  '1565',
  'KS.State',
  'Montes',
  'Plains',
  'W-2',
  'Wage',
  'and',
  'Local',
  'income',
  'ta',
  'tement',
  'Tax',
  'Copy',
  '34947.67',
  'Capy',
  'to',
  'be',
  'fied',
  'with',
  "employee's",
  'State',
  'Income',
  'Tax',
  'Re',
  '2018',
  'City',
  'Local',
  'W-2',
  'and',
  'Tax',
  'Copy',
  'Copy',
  'to',
  'be',
  'filed',
  'with',
  "employee's",
  'City',
  'er',
  'Local',
  'Income',
  'Tax',
  'Retor',
  'OnB',
  'Due.',
  '1565-9098',
  '2018'],
 595)

In [64]:
# Define a function to predict the ner tags for a given transcript
def predict_val(example):
    ner_tags = []
    len_example = len(example)
    if len_example > 300:
        
        example_1 = example[:(len_example//2)]
        example_2 = example[(len_example//2):]
        
        lab_1 = classifier(example_1)
        lab_2 = classifier(example_2)
        
        lab_1 = extract_labels_from_inference(lab_1)
        lab_2 = extract_labels_from_inference(lab_2)
        
        ner_tags += lab_1
        ner_tags += lab_2
    
    else:
        
        lab = classifier(example)
        lab = extract_labels_from_inference(lab)
        ner_tags += lab
    
    return ner_tags

In [65]:
# Get all the tsv files in a given directory

tsv_file = glob.glob('/kaggle/working/val/boxes_transcripts' + '/*.tsv')

In [66]:
len(tsv_file)

0

In [67]:
import os
# Define a function to generate validation tsv files with predicted labels
def generate_val_tsvs(path):
    
    if not os.path.exists('val'):
        os.mkdir('val')
        os.mkdir('val/boxes_transcripts')
    
    directory = path

    tsv_file = glob.glob(directory + '/*.tsv')

    for filename in tsv_file:
        data_i = pd.read_csv(filename, header=None)
        data_i.columns = ['start_index', 'end_index', 'x_top_left', 'y_top_left', 'x_bottom_right', 'y_bottom_right', 'transcript']
        data_i.dropna(subset=['transcript'], inplace=True)
        
        transcript = data_i['transcript'].to_list()
        
        pred = predict_val(transcript)
        
        data_i['field'] = pred
        
        data_i.to_csv(f"val/boxes_transcripts/{filename.split('/')[-1]}", index=False, header=None)

In [68]:
%%time
# Measure the execution time of generating the validation tsv files with labels
generate_val_tsvs('/kaggle/input/demo-data/dataset/val/boxes_transcripts')

/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(

CPU times: user 7min 29s, sys: 571 ms, total: 7min 29s
Wall time: 7min 31s

# <span style="font-family:cursive;text-align:center">⬇️ Generating metrics.tsv</span>

In [69]:
import os
import csv
import pandas as pd

'''
Entities:
1. employerName
2. employerAddressStreet_name
3. employerAddressCity
4. employerAddressState
5. employerAddressZip
6. einEmployerIdentificationNumber
7. employeeName
8. ssnOfEmployee
9. box1WagesTipsAndOtherCompensations
10. box2FederalIncomeTaxWithheld
11. box3SocialSecurityWages
12. box4SocialSecurityTaxWithheld
13. box16StateWagesTips
14. box17StateIncomeTax
15. taxYear
'''



'''
Description: The fuction yields the standard precision, recall and f1 score metrics

arguments:
    TP -> int
    FP -> int
    FN -> int

returns: float, float, float
'''
def performance(TP, FP, FN):
    
    if (TP+FP) == 0:
        precision = 0
    else:
        precision = TP/float((TP+FP))
        
    if (TP+FN) == 0:
        recall = 0
    else:
        recall = TP/float((TP+FN))
    
    if (recall!= 0) and (precision!= 0):
        f1_score = (2.0*precision*recall)/(precision+recall)
    else:
        f1_score = 0
    
    return precision, recall, f1_score
    
    
    
    
'''
Description: The fuction yields a dataframe containing entity-wise performance metrics

arguments:
    true_labels -> list
    pred_labels -> lisyt
    
returns: pandas dataframe
'''
def get_dataset_metrics(true_labels, pred_labels):
    
    metrics_dict = dict()
    
    for true_label, pred_label in zip(true_labels, pred_labels):
        if true_label not in metrics_dict:
            metrics_dict[true_label] = {"TP":0, "FP":0, "FN":0, "Support":0}
        
        if true_label != "OTHER":
            metrics_dict[true_label]["Support"] += 1
            
            if true_label == pred_label:
                metrics_dict[true_label]["TP"] += 1
            
            elif pred_label == "OTHER":
                metrics_dict[true_label]["FN"] += 1
            
        else:
            if pred_label != "OTHER":
                metrics_dict[pred_label]["FP"] += 1
           
    df = pd.DataFrame()
    
    for field in metrics_dict:
        precision, recall, f1_score = performance(metrics_dict[field]["TP"], metrics_dict[field]["FP"], metrics_dict[field]["FN"])
        support = metrics_dict[field]["Support"]
        
        if field != "OTHER":
            temp_df = pd.DataFrame([[precision, recall, f1_score, support]], columns=["Precision", "Recall", "F1-Score", "Support"], index=[field])
#             df = df.append(temp_df)
            df = pd.concat([df, temp_df])
    
    return df




'''
Description: The fuction yields a dataframe containing entity-wise performance metrics for a single document
(make sure the doc id is the same)

arguments:
    doc_true -> tsv file with with labels in the last column (8 th column (1-indexed))
    doc_pred -> tsv file with labels in the last column (8 th column (1-indexed)), as predicted by the model
    
returns: list, list
'''
def get_doc_labels(doc_true, doc_pred):

    true_labels = [row[-1] for row in csv.reader(open(doc_true, "r"))]
    pred_labels = [row[-1] for row in csv.reader(open(doc_pred, "r"))]

    return true_labels, pred_labels

'''
Description: The fuction yields a dataframe containing entity-wise performance metrics for all documents
(make sure the doc ids are the same in both the paths)

arguments:
    doc_true -> string (directory containing the ground truth tsv files)
    doc_pred -> string (directory containing the predicted tsv files)
    save -> bool (saves the metrics file in your working directory)
returns: pandas dataframe
'''
def get_dataset_labels(true_path, pred_path, save=False):
    
    y_true, y_pred = [], []
    
    for true_file in os.listdir(true_path):
        for pred_file in os.listdir(pred_path):
            if (".tsv" in true_file) and (".tsv" in pred_file):
                if true_file == pred_file:
                    
                    true_file, pred_file = f"{true_path}/{true_file}", f"{pred_path}/{pred_file}"
                    true_labels, pred_labels = get_doc_labels(true_file, pred_file)
                    
                    y_true.extend(true_labels)
                    y_pred.extend(pred_labels)
            
    df = get_dataset_metrics(y_true, y_pred)
    print(df)
    if save == True:
        df.to_csv("eval_metrics.tsv")



if __name__ == "__main__":
    
    # template to run your own evaluation

    doc_true = f"/kaggle/input/demo-data/dataset/val_w_ann/boxes_transcripts_labels"
    doc_pred = f"/kaggle/working/val/boxes_transcripts"

    get_dataset_labels(doc_true, doc_pred, save=True)

                                    Precision    Recall  F1-Score  Support
box1WagesTipsAndOtherCompensations   0.088235  0.009259  0.016760      359
box2FederalIncomeTaxWithheld         0.000000  0.000000  0.000000      368
box3SocialSecurityWages              0.012324  0.082840  0.021456      353
box4SocialSecurityTaxWithheld        0.012821  0.047761  0.020215      359
employerName                         0.122807  0.011532  0.021084      696
employerAddressStreet_name           0.013468  0.005755  0.008065      786
employerAddressCity                  0.030211  0.034843  0.032362      305
employerAddressState                 0.000000  0.000000  0.000000      196
employerAddressZip                   0.040284  0.094444  0.056478      199
einEmployerIdentificationNumber      0.023969  0.142045  0.041017      195
ssnOfEmployee                        0.027484  0.080745  0.041009      173
employeeName                         0.000000  0.000000  0.000000      404
box16StateWagesTips                  0.000000  0.000000  0.000000      362
box17StateIncomeTax                  0.000000  0.000000  0.000000      337
taxYear                              0.055310  0.147059  0.080386      173

In [70]:
eval_df = pd.read_csv("/kaggle/working/eval_metrics.tsv")
eval_df

                            Unnamed: 0  Precision    Recall  F1-Score  Support
0   box1WagesTipsAndOtherCompensations   0.088235  0.009259  0.016760      359
1         box2FederalIncomeTaxWithheld   0.000000  0.000000  0.000000      368
2              box3SocialSecurityWages   0.012324  0.082840  0.021456      353
3        box4SocialSecurityTaxWithheld   0.012821  0.047761  0.020215      359
4                         employerName   0.122807  0.011532  0.021084      696
5           employerAddressStreet_name   0.013468  0.005755  0.008065      786
6                  employerAddressCity   0.030211  0.034843  0.032362      305
7                 employerAddressState   0.000000  0.000000  0.000000      196
8                   employerAddressZip   0.040284  0.094444  0.056478      199
9      einEmployerIdentificationNumber   0.023969  0.142045  0.041017      195
10                       ssnOfEmployee   0.027484  0.080745  0.041009      173
11                        employeeName   0.000000  0.000000  0.000000      404
12                 box16StateWagesTips   0.000000  0.000000  0.000000      362
13                 box17StateIncomeTax   0.000000  0.000000  0.000000      337
14                             taxYear   0.055310  0.147059  0.080386      173